Workflows: Test for Fedora and Pop configurations
elementary/appcenter pull request #1679
Opened 2021-09-15 20:25 UTC by danrabbit

Add builds for downstream configurations to make sure we don't break stuff

2021-09-15 20:26 UTC, danrabbit commented
@decathorpe do you use other options besides `homepage=false`?

2021-09-15 20:46 UTC, decathorpe commented
Yes, I've been additionally using `-Dpayments=false -Dcurated=false`, though I'm thinking about changing at least some of those flags for Fedora builds in the near future.

2021-09-16 20:49 UTC, cassidyjames requested changes

2021-09-16 20:49 UTC, cassidyjames commented on .github/workflows/main.yml
> +        meson configure -Dcurated=false -Dhomepage=false -Dpayments=false  build
Since the `homepage` build flag was dropped:

```suggestion
        meson configure -Dcurated=false -Dpayments=false build
```

2021-09-16 20:49 UTC, cassidyjames commented on .github/workflows/main.yml
> +        meson configure -Dcurated=false -Dpayments=false -Dsharing=false build
Should also test with `name` build flag, even though it _shouldn't_ affect building.

```suggestion
        meson configure -Dcurated=false -Dpayments=false -Dsharing=false -Dname=Pop\!_OS build
```

2021-09-17 17:26 UTC, cassidyjames approved these changes

2021-09-17 17:28 UTC, merged