Make back button behaviour more consistant
elementary/appcenter pull request #1752
Opened 2021-11-11 20:16 UTC by 13r0ck

Fixes #1750 and #1751

2021-12-02 22:18 UTC, cassidyjames requested changes
@13r0ck thanks for submitting this! However, I'm still seeing some weird behavior here. When navigating from Home → Category (e.g. Accessories) → Search, the back button here still says "Home," and takes you home. However, I'd expect it to back out of the search and bring you back to the category.

If that's a much more invasive change I'd consider merging this as-is to fix the listed issues, but it still feels off, so I wonder if we can take the time to make it right.

2021-12-02 22:33 UTC, 13r0ck commented
Ya it will take me a bit to get around to that, but I will make it happen. :smile:

2021-12-03 03:37 UTC, 13r0ck commented
Nevermind I fixed it today

2021-12-10 06:17 UTC, cassidyjames requested changes
Thanks again for this! I've taken an initial look and noticed some small fixes. I'll give it some testing but I think I'd like a more thorough review from @elementary/desktop-developers.

2021-12-10 06:17 UTC, cassidyjames commented on src/MainWindow.vala
> +        search_view.category_return_clicked.connect(show_category);
Lint: space before paren

```suggestion
        search_view.category_return_clicked.connect (show_category);
```

2021-12-10 06:17 UTC, cassidyjames commented on src/Views/SearchView.vala
> +                    subview_entered (_(current_category.name), true, current_category.name);
If I'm reading this correctly, this should not be marked as translatable 

```suggestion
                    subview_entered (current_category.name, true, current_category.name);
```

2021-12-10 06:17 UTC, cassidyjames commented on src/Views/SearchView.vala
> +            subview_entered (_(current_category.name), true, current_category.name);
Same as above

```suggestion
            subview_entered (current_category.name, true, current_category.name);
```

2021-12-10 06:21 UTC, cassidyjames commented
I can confirm that this seems to fix the back button labeling and behavior, though!

2021-12-10 17:34 UTC, 13r0ck commented
Ah I didn't know that `_()` meant the string was translatable. Thank you for the review and teaching me!

2021-12-18 00:57 UTC, zeebok reviewed
I think the code here looks good. I do wonder why some kind of stack isn't used to track previously visited views but that is something to explore another time. @cassidyjames if your tests are showing green I think this is good to go!

2022-01-06 23:15 UTC, cassidyjames approved these changes

2022-01-06 23:17 UTC, merged