Move get_packages from AbstractAppList to AppListUpdateView
elementary/appcenter pull request #1912
Opened 2022-09-02 17:09 UTC by danrabbit

Only used in one implementation so move it from the abstract list. We have a null check with a continue here so I'm assuming this type of cast is intentional, maybe because row headers are listbox children?

2022-09-02 17:47 UTC, jeremypw commented on src/Views/AppListUpdateView.vala
> +                }
Maybe better to replace this with 
```
if (!child is Widgets.PackageRow) {
    continue;
}

row = (Widgets.PackageRow)child;
```

2022-09-02 17:51 UTC, danrabbit commented on src/Views/AppListUpdateView.vala
> +                }
Yeah that's much more explicit. Thanks!

2022-09-02 17:54 UTC, jeremypw requested changes
Functionally equivalent but see code style suggestion.

2022-09-03 07:41 UTC, jeremypw approved these changes

2022-09-03 07:41 UTC, merged