Release 7.2.0
elementary/appcenter pull request #1992
Opened 2023-02-06 20:52 UTC by danirabbit

Contains a fix for a Flatpak update issue

2023-02-06 23:59 UTC, lenemter requested changes
Update version in `meson.build` please :)

2023-02-07 00:13 UTC, danirabbit commented
Oops, thank you!

2023-02-07 00:28 UTC, lenemter approved these changes
Looks good. But we need to wait for translation update before release

2023-02-08 22:12 UTC, lenemter approved these changes

2023-02-08 22:14 UTC, merged