Remove OS updates
elementary/appcenter pull request #2111
Opened 2024-02-06 23:57 UTC by danirabbit

This doesn't completely remove packagekit because we use it for UbuntuDrivers

2024-02-07 18:42 UTC, danirabbit commented
@leolost2605 I don't think runtime updates should be asking for a reboot right? Should we remove the restart notification completely?

2024-02-07 19:36 UTC, leolost2605 commented
@danirabbit I can't comment on runtime updates but AFAIK the only thing that would need a reboot are drivers and with elementary/settings-daemon#132 they can be removed as well so we might just remove it know 🤷

2024-02-07 19:49 UTC, leolost2605 requested changes
Looks good for now but I think we can remove even a bit more? For example we could just make packagekit return in cache refresh since it's not needed for ubuntu drivers i think?

2024-02-07 19:49 UTC, leolost2605 commented on src/Core/UpdateManager.vala
>  #if PACKAGEKIT_BACKEND
I think we can remove all of this?

2024-02-11 12:24 UTC, leolost2605 approved these changes
LGTM

2024-02-11 12:26 UTC, merged